### ISSUE TITLE
Error deploying CSS

### ISSUE THREAD

**Issue by MattTurnure** [msrivastav13/DX-Code-Companion#4]
After creating a CSS file on a LWC, `sfdx deploy:lwc -p "/path/to/file.css" results in this error:

`TypeError: Cannot read property 'FilePath' of undefined`

**Comment by msrivastav13** [comment]
Thank you @MattTurnure .Does this happen if lwc is first deploy or even after the lwc is in server?

**Comment by MattTurnure** [comment]
It seems to only happen on initial deploy. Steps to recreate:

1. `command+shift+p` to bring up SFDX dialogue in VSC
2. Selected `SFDX Create Lightning Web Component`
3. Set path to default lwc
4. Entered name of component (test)
5. A LWC is generated with 3 files: test.html, test.js, and test.js-meta.xml (no css)
6. Create a CSS file in the LWC directory generated (test.css)
7. Save the CSS file.

The plugin fires `sfdx deploy:lwc -p "/Users/matt/workspaces/myRepo/force-app/main/default/lwc/test/test.css"` then throws the error.

If I deploy using sfdx force:source:push -p test first, then mo-dx-plugin works with subsequent saves.

**Comment by msrivastav13** [comment]
Thanks @MattTurnure once again for issue log .

**Update** 

I believe i have fixed the issue with the new update . Note that since plugins was affected you will need to update the mo-dx-plugin using 

`sfdx plugins:update mo-dx-plugin`

After update double check that you are on v 0.1.7 version which is the latest . 

If you have trouble with update then you can also uninstall using `sfdx plugins:uninstall mo-dx-plugin` and then reinstall using `sfdx plugins:install mo-dx-plugin`.

Also note that v 0.1.7 made some significant enhancements to way i used to log errors . Everything will use oclif table format . Let me know if you find any issues in any of command .

I will close it once i get thumbs up from you :) . Thanks again !!!!!!!

**Comment by msrivastav13** [comment]
Here is how the errors would look now

![screen shot 2019-02-16 at 10 50 28 am](https://user-images.githubusercontent.com/2276156/52902010-c63b9000-31d8-11e9-81dc-207e79cb15cf.png)
![screen shot 2019-02-16 at 10 42 56 am](https://user-images.githubusercontent.com/2276156/52902011-c63b9000-31d8-11e9-8719-f06d5c9eaf8b.png)

**Comment by msrivastav13** [comment]
@MattTurnure I am closing this since I think it looks fixed to me . If you still see something weird please reopen . Thank you .
